# NumPy: the absolute basics for beginners

## This tutorial in particular repeats [NumPy: the absolute basics for beginners](https://numpy.org/doc/stable/user/absolute_beginners.html) a lot from the official site of NumPy.

***

We shorten the imported name to `np` for better readability of code using NumPy. This is a widely adopted convention that you should follow so that anyone working with your code can easily understand it.

In [2]:
# import numpy
import numpy as np

### How to create a basic array

> `np.array()`

> `np.zeros()`

> `np.ones()`

> `np.empty()`

> `np.arange()`

> `np.linspace()`

In [3]:
np.array([[1, 2, 3, 4], [1, 2, 3, 4]])

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [7]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Or even an empty array! The function `empty` creates an array whose initial content is random and depends on the state of the memory. **The reason to use empty over zeros (or something similar) is speed** - just make sure to fill every element afterwards!#### 

In [8]:
np.empty([3, 2])

array([[4.67121671e-310, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000]])

In [9]:
# create range of elements
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(2, 9, 3)

array([2, 5, 8])

In [14]:
np.linspace(1, 2, 5, endpoint=True)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

#### Specifying your data type

> dtype

In [16]:
np.ones(2, dtype=np.float32)

array([1., 1.], dtype=float32)

### Adding, removing, and sorting elements 

> `numpy.sort(a, axis=-1, kind=None, order=None)`

Return a sorted copy of an array.

**Parameters:**
1. **a : array_like**

Array to be sorted.

2. **axis : int or None, optional**

Axis along which to sort. If None, the array is flattened before sorting. The default is -1, which sorts along the last axis.

3. **kind : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional**

Sorting algorithm. The default is ‘quicksort’. Note that both ‘stable’ and ‘mergesort’ use timsort or radix sort under the covers and, in general, the actual implementation will vary with data type. The ‘mergesort’ option is retained for backwards compatibility.

Changed in version 1.15.0.: The ‘stable’ option was added.

4. **order : str or list of str, optional**

When a is an array with fields defined, this argument specifies which fields to compare first, second, etc. A single field can be specified as a string, and not all fields need be specified, but unspecified fields will still be used, in the order in which they come up in the dtype, to break ties.

> `numpy.concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")`

Join a sequence of arrays along an existing axis.



In [17]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [18]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [19]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [21]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [38]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6], [7, 8]])
np.concatenate((x, y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### How do you know the shape and size of an array?

> `ndarray.ndim`

will tell you the number of axes, or dimensions, of the array.

> `ndarray.size`

will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

> `ndarray.shape`

will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [47]:
array_example = np.arange(24).reshape(2, 3, -1)
array_example

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
array_example.ndim

3

In [49]:
array_example.size

24

In [50]:
array_example.shape

(2, 3, 4)

### Can you reshape an array?


> `numpy.reshape(a, newshape, order='C')`

will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array.

**Parameters :**

1. **a : array_like**

Array to be reshaped.

2. **newshape : int or tuple of ints**

The new shape should be compatible with the original shape. If an integer, then the result will be a 1-D array of that length. One shape dimension can be -1. In this case, the value is inferred from the length of the array and remaining dimensions.

3. **order : {‘C’, ‘F’, ‘A’}, optional** 

Read the elements of a using this index order, and place the elements into the reshaped array using this index order. ‘C’ means to read / write the elements using C-like index order, with the last axis index changing fastest, back to the first axis index changing slowest. ‘F’ means to read / write the elements using Fortran-like index order, with the first index changing fastest, and the last index changing slowest. Note that the ‘C’ and ‘F’ options take no account of the memory layout of the underlying array, and only refer to the order of indexing. ‘A’ means to read / write the elements in Fortran-like index order if a is Fortran contiguous in memory, C-like order otherwise.

In [53]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [54]:
b = a.reshape(3, 2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [56]:
np.reshape(a, newshape=(1, 6), order='C')

array([[0, 1, 2, 3, 4, 5]])

### How to convert a 1D array into a 2D array (how to add a new axis to an array)

> `np.newaxis` 

> `np.expand_dims`

Using `np.newaxis` will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [57]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [59]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis. For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:

In [63]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [64]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

You can also expand an array by inserting a new axis at a specified position with `np.expand_dims`.

In [65]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [66]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [67]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [97]:
d = np.expand_dims(a, axis=(0, 2, 3))
d.shape

(1, 6, 1, 1)

In [99]:
print(d)

[[[[1]]

  [[2]]

  [[3]]

  [[4]]

  [[5]]

  [[6]]]]


In [100]:
d[0, 4, 0, 0]

5

### Indexing and slicing

In [103]:
data = np.array([1, 2, 3])

In [104]:
data[1]

2

In [105]:
data[0:2]

array([1, 2])

In [106]:
data[1:]

array([2, 3])

In [107]:
data[-2:]

array([2, 3])

![](./images/np_indexing.png)

You may want to take a section of your array or specific array elements to use in further analysis or additional operations. To do that, you’ll need to subset, slice, and/or index your arrays.

If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

For example, if you start with this array:

In [108]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

You can easily print all of the values in the array that are less than 5.


In [109]:
print(a[a < 5])

[1 2 3 4]


You can also select, for example, numbers that are equal to or greater than 5, and use that condition to index an array.



In [112]:
five_up = (a >= 5)
five_up

array([[False, False, False, False],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [111]:
print(a[five_up])


[ 5  6  7  8  9 10 11 12]


In [113]:
divisible_by_2 = a[a%2==0]
divisible_by_2

array([ 2,  4,  6,  8, 10, 12])

In [114]:
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [115]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


You can also use `np.nonzero()` to select elements or indices from an array.

Starting with this array:

In [123]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a > 5)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [124]:
b

(array([1, 1, 1, 2, 2, 2, 2]), array([1, 2, 3, 0, 1, 2, 3]))

In [125]:
a[b]

array([ 6,  7,  8,  9, 10, 11, 12])

In this example, a tuple of arrays was returned: one for each dimension. The first array represents the row indices where these values are found, and the second array represents the column indices where the values are found.

If you want to generate a list of coordinates where the elements exist, you can zip the arrays, iterate over the list of coordinates, and print them. For example:

In [126]:
list_of_coordinates= list(zip(b[0], b[1]))

In [127]:
for coord in list_of_coordinates:
    print(coord)

(1, 1)
(1, 2)
(1, 3)
(2, 0)
(2, 1)
(2, 2)
(2, 3)


### How to create an array from existing data¶
