# Numpy beginner tutorial
## This tutorial in particular repeats [numpy quickstart](https://numpy.org/devdocs/user/quickstart.html) a lot from the official site of NumPy.

In [4]:
# imports
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

### Basics

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of non-negative integers. In NumPy dimensions are called `axes`.

In [5]:
# for example: the array has 2 axes. The first axis has a length of 2, the second axis has a length of 3.
[[1., 0., 0.],
 [0., 1., 0.]]

[[1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]

NumPy’s array class is called `ndarray`. It is also known by the alias array. Note that `numpy.array` **is not** the same as the Standard Python Library class `array.array`

The more important attributes of an ndarray object are:

***

> `ndarray.ndim`

the number of axes (dimensions) of the array.

> `ndarray.shape`

the dimensions of the array. This is a tuple of integers indicating the size of the array in each dimension. For a matrix with n rows and m columns, `shape` will be `(n,m)`. The length of the `shape` tuple is therefore the number of axes, `ndim`.

> `ndarray.size`

the total number of elements of the array. This is equal to the product of the elements of `shape`.

> `ndarray.dtype`

an object describing the type of the elements in the array. One can create or specify dtype’s using standard Python types. **Additionally** NumPy provides types of its own. **numpy.int32, numpy.int16, and numpy.float64 are some examples**.

> `ndarray.itemsize`

the size in bytes of each element of the array. For example, an array of elements of type `float64` has `itemsize` 8 (=64/8), while one of type `complex32` has `itemsize 4` (=32/8). It is equivalent to `ndarray.dtype.itemsize`.

> `ndarray.data`

the buffer containing the actual elements of the array. Normally, we won’t need to use this attribute because we will access the elements in an array using indexing facilities.


In [7]:
lst = np.arange(15).reshape(3, 5)
lst

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
lst.shape

(3, 5)

In [9]:
lst.size

15

In [12]:
lst.dtype

dtype('int64')

In [13]:
lst.itemsize

8

In [15]:
lst.data

In [16]:
type(lst)

numpy.ndarray

In [20]:
# create numpy array
basic_lst = [1, 2, 3, 4]
own_lst = np.array(basic_lst)

own_lst

array([1, 2, 3, 4])

In [19]:
type(own_lst)

numpy.ndarray

### Array Creation

In [24]:
# create array using np.array function
int_lst = np.array([1, 2, 3])
int_lst

array([1, 2, 3])

In [23]:
int_lst.dtype

dtype('int64')

In [26]:
float_lst = np.array([1., 2., 3.])
float_lst

array([1., 2., 3.])

In [27]:
float_lst.dtype

dtype('float64')

A frequent error consists in calling `array` with multiple arguments, rather than providing a single sequence as an argument.

In [29]:
# WRONG
np.array(1, 2, 3, 4)

TypeError: array() takes from 1 to 2 positional arguments but 4 were given

In [30]:
# RIGHT
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

`array` transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three-dimensional arrays, and so on.

In [36]:
# like tuples
lst_2dim = np.array([(1, 2, 3), (4, 5, 6)])
lst_2dim

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
# like list
lst_2dim = np.array([[1, 2, 3], [4, 5, 6]])
lst_2dim

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
lst_2dim.ndim

2

In [40]:
#The type of the array can also be explicitly specified at creation time:
complex_lst = np.array([1, 2, 3, 4], dtype=complex)
complex_lst

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])